name: Golang CI

on:
  workflow_call:
    inputs:
      go-version:
        description: 'The version of Go to use'
        default: 'stable'
        type: string
      use-private-module:
        description: 'Flag to indicate if a private module should be used in the build'
        default: false
        type: boolean
      github-app-id:
        description: 'The ID of the GitHub App to use for authentication'
        type: number
      ecr-repository:
        description: 'The name of the ECR repository to push the Docker image to'
        required: true
        type: string
      aws-region:
        description: 'The AWS region where the ECR repository is located'
        default: ap-south-1
        type: string
      dockerfile:
        description: 'The path to the Dockerfile to use for building the Docker image'
        default: Dockerfile
        type: string
      platforms:
        description: 'The target platforms for the Docker image build (e.g., linux/amd64, linux/arm64)'
        default: linux/amd64
        type: string
      prefix:
        description: 'A prefix to use for the Docker image tags'
        default: sha
        type: string
      tag-type:
        description: 'The type of build (e.g., release, snapshot)'
        default: sha
        type: string
    secrets:
      APP_PRIVATE_KEY:
        description: 'The private key of the GitHub App'
      ASSUME_ROLE:
        description: 'The role to assume for AWS operations'
        required: true

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write
  
jobs:
  lint:
    uses: ./.github/workflows/golangci-lint.yml
    with:
      go-version: ${{ inputs.go-version }}
      use-private-module: ${{ inputs.use-private-module }}
      github-app-id: ${{ inputs.github-app-id }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

  test:
    uses: ./.github/workflows/golangci-test.yml
    needs: lint
    with:
      go-version: ${{ inputs.go-version }}
      use-private-module: ${{ inputs.use-private-module }}
      github-app-id: ${{ inputs.github-app-id }}
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

  build:
    uses: ./.github/workflows/golangci-build.yml
    needs: test
    with:
      ecr-repository: ${{ inputs.ecr-repository }}
      aws-region: ${{ inputs.aws-region }}
      dockerfile: ${{ inputs.dockerfile }}
      platforms: ${{ inputs.platforms }}
      prefix: ${{ inputs.prefix }}
      tag-type: ${{ inputs.tag-type }}
      use-private-module: ${{ inputs.use-private-module }}
      github-app-id: ${{ inputs.github-app-id }}
    secrets:
      ASSUME_ROLE: ${{ secrets.ASSUME_ROLE }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}